---
title: "p8105_hw6_brm2150"
author: "Brooklynn McNeil"
date: "2024-11-19"
output: github_document
---
```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  comment = '', fig.width = 8, fig.height = 6, out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

## Problem 2

Load the homicide data. Create a binary variable for the status for solved/not solved. Filter out cities that don't report race, and only include Black and White races

```{r}
url = "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"
homicide_dat = 
  read_csv(url, na = "Unknown") |>
  mutate(city_state = str_c(city, ", ", state),
         status = case_when(
           disposition %in% c("Closed without arrest", "Closed by arrest") ~ 0,
           disposition == "Open/No arrest" ~ 1
           )) |>
  filter(city_state != c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"),
         victim_race %in% c("White", "Black"))

head(homicide_dat)
```
Create a logistic regression for `status` as the outcome and `age`, `race`, and `sex` as predictors for Baltimore, MD. 

```{r}
baltimore_glm = 
  homicide_dat |>
  filter(city_state == "Baltimore, MD") |>
  glm(status ~ victim_age + victim_race + victim_sex, data = _, family = "binomial")

broom::tidy(baltimore_glm)

## need to add in the odds ration using exp()
```


## Problem 3